const historyData = {
  "Afghanistan": "Afghanistan has tall mountains and was part of the Silk Road, a super cool trade route from ancient times!",
  "Armenia": "Armenia was the first country in the world to officially become Christian!",
  "Azerbaijan": "Azerbaijan is called the Land of Fire because it has natural gas flames that burn from the ground!",
  "Bahrain": "Bahrain is a tiny island nation famous for pearls and ancient forts! Did you know pearls used to be more valuable than gold?",
  "Baikonur":"The Baikonur Cosmodrome is a spaceport operated by Russia within Kazakhstan.",
  "Bangladesh": "Bangladesh is home to the Royal Bengal Tiger and has the largest river delta in the world!",
  "Bhutan": "Bhutan measures happiness instead of money! It's full of beautiful mountains and Buddhist temples.",
  "Brunei": "Brunei has a golden palace with 1,788 rooms! Imagine playing hide and seek there!",
  "Cambodia": "Cambodia has Angkor Wat, one of the biggest temples in the world! It’s like a lost city from an adventure movie!",
  "China": "China is home to pandas, the Great Wall, and kung fu! It also invented paper, fireworks, and noodles!",
  "Cyprus": "Cyprus has beautiful beaches and is known as the mythical birthplace of Aphrodite, the Greek goddess of love!",
  "Georgia": "Georgia has one of the oldest winemaking traditions in the world! Plus, they have their own unique alphabet!",
  "India": "India gave us chess, yoga, and the Taj Mahal! It's also home to the spiciest foods and the Bollywood movie industry!",
  "Indonesia": "Indonesia has over 17,000 islands! It's also home to Komodo dragons – the biggest lizards in the world!",
  "Iran": "Iran, once called Persia, gave the world beautiful carpets, poetry, and Persian cats!",
  "Iraq": "Iraq is where some of the oldest civilizations started, including Mesopotamia, home to the first writing system!",
  "Israel": "Israel has some of the oldest cities in the world, including Jerusalem! It’s a special place for many religions.",
  "Japan": "Japan is the land of samurai, sushi, and ninjas! It also has Mount Fuji and invented video games!",
  "Jordan": "Jordan is home to Petra, a magical city carved into pink rocks!",
  "Kazakhstan": "Kazakhstan is where the first human went to space! It also has endless steppes (grasslands).",
  "Kuwait": "Kuwait is rich in oil and has some of the world’s tallest buildings!",
  "Kyrgyzstan": "Kyrgyzstan is full of mountains and people still live in yurts, which are cool round tents!",
  "Laos": "Laos is known as the Land of a Million Elephants! It's also famous for stunning waterfalls!",
  "Lebanon": "Lebanon is home to the oldest continuously inhabited city, Byblos! Plus, it has famous cedar trees!",
  "Malaysia": "Malaysia has rainforests full of monkeys! It’s also home to the tall Petronas Towers.",
  "Mongolia": "Mongolia was once ruled by Genghis Khan, who created the largest empire in history!",
  "Myanmar": "Myanmar has the Golden Rock, a giant boulder that seems to float on a cliff!",
  "Nepal": "Nepal is home to Mount Everest, the tallest mountain on Earth!",
  "North Korea": "North Korea is one of the most secretive countries in the world. Most people don’t have internet or social media!",
  "Oman": "Oman has a long desert and some of the oldest castles in the world!",
  "Pakistan": "Pakistan has K2, the second tallest mountain in the world! It’s also home to ancient civilizations!",
  "Palestine": "Palestine is a place full of history and holy sites, like Bethlehem and Jerusalem.",
  "Philippines": "The Philippines has over 7,000 islands! It’s also the texting capital of the world!",
  "Qatar": "Qatar is home to super futuristic buildings and hosted the 2022 FIFA World Cup!",
  "Saudi Arabia": "Saudi Arabia is home to Mecca, the holiest city for Muslims. It’s also full of huge deserts!",
  "Singapore": "Singapore is a tiny but super modern city! It has gardens with giant glowing trees!",
  "South Korea": "South Korea is famous for K-Pop, kimchi, and high-tech gadgets!",
  "Sri Lanka": "Sri Lanka is called the Pearl of the Indian Ocean and is home to wild elephants!",
  "Syria": "Syria has some of the oldest ruins in the world! It was part of the famous Silk Road trade route.",
  "Taiwan": "Taiwan is a beautiful island known for its yummy night markets, tall mountains, and super cool technology. It’s also famous for bubble tea, a sweet drink with chewy balls! Taiwan has a mix of old temples and modern cities. It’s a wonderful country with lots to discover and learn about!",
  "Tajikistan": "Tajikistan is a country full of massive mountains and is part of the ancient Silk Road!",
  "Thailand": "Thailand is known for golden temples, floating markets, and being the only country in Southeast Asia that was never colonized!",
  "Timor-Leste": "Timor-Leste, also called East Timor, is one of the newest countries in the world! It’s known for its beaches, mountains, and friendly people. It became independent in 2002 after a long struggle.",
  "Turkey": "Fun fact: The bird 'turkey' is NOT from Turkey! Turkey is where ancient Troy was, and where East meets West!",
  "Turkmenistan": "Turkmenistan is known for its huge deserts and ancient cities. In the past, it was part of the Silk Road, where traders from all over the world came to buy and sell goods.",
  "United Arab Emirates": "The UAE has the tallest building in the world!",
  "Uzbekistan": "Uzbekistan is full of beautiful blue-tiled cities and was an important stop on the Silk Road!",
  "Vietnam": "Vietnam is famous for delicious Pho soup, floating villages, and cool dragon bridges!",
  "Yemen": "Yemen is home to ancient skyscrapers made of mud! They're over 500 years old and still standing!"
};


export default historyData;
