const historyData = {
  "Afghanistan": "Afghanistan has a long history, dating back to the ancient Persian Empire and later becoming a strategic point along the Silk Road.",
  "Armenia": "Armenia was the first nation to adopt Christianity in 301 AD and has a rich cultural history dating back thousands of years.",
  "Azerbaijan": "Azerbaijan has a diverse history, influenced by Persian, Russian, and Ottoman empires, and is known for its rich oil reserves.",
  "Bahrain": "Bahrain was a key trading hub in the Persian Gulf and has a history dating back to the ancient Dilmun civilization.",
  "Bangladesh": "Bangladesh was part of British India until its independence in 1971, after a brutal war of independence.",
  "Bhutan": "Bhutan, known for its unique approach to measuring happiness, has been a kingdom with strong Buddhist traditions.",
  "Brunei": "Brunei's history is shaped by its strategic position in Southeast Asia and its wealth from oil production.",
  "Cambodia": "Cambodia is known for the ancient Khmer Empire and the famous Angkor Wat temple complex, which dates back to the 12th century.",
  "China": "China has one of the world's oldest continuous civilizations, with a history spanning over 5,000 years, including the dynastic periods and the rise of communism.",
  "Cyprus": "Cyprus has been influenced by Greek, Roman, and Ottoman cultures and has a divided history between Greek and Turkish populations.",
  "Georgia": "Georgia has a rich medieval history and is considered one of the oldest Christian states, with a unique language and culture.",
  "India": "India is known for its diverse culture, ancient civilizations like the Indus Valley, and the birth of major religions such as Hinduism, Buddhism, and Sikhism.",
  "Indonesia": "Indonesia consists of over 17,000 islands, with a history influenced by Hinduism, Islam, and Dutch colonization.",
  "Iran": "Iran, historically known as Persia, has a rich cultural and political history, including the rise and fall of powerful empires like the Achaemenids.",
  "Iraq": "Iraq is home to some of the oldest civilizations, including Mesopotamia, and was the birthplace of early writing and agriculture.",
  "Israel": "Israel has a history deeply tied to the Bible, and its modern state was established in 1948, with significant geopolitical importance.",
  "Japan": "Japan has a history shaped by the Edo period, feudalism, and the rise of modern Japan after the Meiji Restoration in the late 19th century.",
  "Jordan": "Jordan's history includes the ancient Nabatean civilization, and the country has been a central player in the Middle Eastern geopolitics.",
  "Kazakhstan": "Kazakhstan was part of the Soviet Union and became an independent republic in 1991, known for its vast steppes and natural resources.",
  "Kuwait": "Kuwait was a British protectorate and gained independence in 1961. It was invaded by Iraq in 1990, but later liberated by a U.S.-led coalition.",
  "Kyrgyzstan": "Kyrgyzstan is a mountainous country with a history influenced by Russian and Soviet rule, gaining independence in 1991.",
  "Laos": "Laos was part of French Indochina and is known for its natural beauty and its role in the Vietnam War.",
  "Lebanon": "Lebanon has a history of ancient Phoenician civilization, followed by Ottoman and French colonial influences, with complex modern political dynamics.",
  "Malaysia": "Malaysia was formed in 1963 and has a diverse cultural history influenced by Malay, Chinese, Indian, and European influences.",
  "Maldives": "The Maldives has a history shaped by its isolation in the Indian Ocean and its role as a prominent tourist destination.",
  "Mongolia": "Mongolia was the heart of the Mongol Empire, which was once the largest contiguous empire in world history.",
  "Myanmar": "Myanmar, formerly Burma, has a complex history of military rule and recent transitions toward democracy, but it continues to face political challenges.",
  "Nepal": "Nepal is the birthplace of Buddha and home to the Himalayas, including Mount Everest, the world's highest peak.",
  "North Korea": "North Korea, a communist state, emerged after World War II and has been ruled by the Kim family since its founding.",
  "Oman": "Oman has a history as an important trading hub in the Arabian Peninsula and is known for its ancient maritime culture.",
  "Pakistan": "Pakistan was formed in 1947 as a homeland for Muslims from British India, and its history has been shaped by its relationship with India and its military rule.",
  "Palestine": "Palestine's history is deeply tied to religious and territorial disputes, particularly between Israelis and Arabs, with ongoing conflicts in the region.",
  "Philippines": "The Philippines has a history shaped by Spanish colonization, U.S. rule, and independence in 1946, with a rich cultural diversity.",
  "Qatar": "Qatar's history is rooted in its role as a pearl diving and trading center, but it has transformed into a modern state through its vast natural gas reserves.",
  "Russia": "Russia, the largest country in the world, has a rich history from Tsarist times to its Soviet past and its current political landscape.",
  "Saudi Arabia": "Saudi Arabia was founded in 1932 and has since become a global power due to its oil reserves, with a deeply rooted Islamic heritage.",
  "Singapore": "Singapore became an independent city-state in 1965, rapidly transforming into a global financial hub.",
  "South Korea": "South Korea emerged from the Korean War as a democratic nation, becoming a major economic power and technological leader.",
  "Sri Lanka": "Sri Lanka's history includes ancient kingdoms, colonial rule by the Portuguese, Dutch, and British, and a civil war that ended in 2009.",
  "Syria": "Syria has a long history as a crossroads of ancient civilizations and has been embroiled in a devastating civil war since 2011.",
  "Tajikistan": "Tajikistan, part of the Soviet Union until 1991, has a history marked by Persian influence and rugged mountainous landscapes.",
  "Thailand": "Thailand has never been colonized and has a rich history influenced by Buddhism and monarchy.",
  "Timor-Leste": "Timor-Leste became independent in 2002 after a violent struggle for independence from Indonesia.",
  "Turkey": "Turkey, once the center of the Byzantine Empire and the Ottoman Empire, became a republic in 1923 under Mustafa Kemal Atatürk.",
  "Turkmenistan": "Turkmenistan gained independence from the Soviet Union in 1991 and has a history shaped by nomadic cultures.",
  "United Arab Emirates": "The UAE was formed in 1971 and has grown into a prosperous nation due to its oil reserves, with a modern and cosmopolitan society.",
  "Uzbekistan": "Uzbekistan, an ancient center of the Silk Road, became independent in 1991 after the collapse of the Soviet Union.",
  "Vietnam": "Vietnam's history includes ancient kingdoms, French colonization, and a long war of independence, culminating in reunification in 1975.",
  "Yemen": "Yemen has a rich ancient history, but its modern history has been marked by political instability and a humanitarian crisis in recent years.",
};

export default historyData;
